"""empty message

Revision ID: 369b8c44a23e
Revises: 
Create Date: 2025-09-25 07:30:41.448348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '369b8c44a23e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pacotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Pessoas', sa.String(), nullable=True),
    sa.Column('Nome', sa.String(), nullable=True),
    sa.Column('Destino', sa.String(), nullable=True),
    sa.Column('preco', sa.Integer(), nullable=True),
    sa.Column('disponibilidade', sa.Boolean(), nullable=False),
    sa.Column('categoria', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('sobrenome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('senha', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('pacotes')
    # ### end Alembic commands ###
