"""empty message

Revision ID: 394b365ba277
Revises: 369b8c44a23e
Create Date: 2025-09-25 08:00:44.017615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '394b365ba277'
down_revision = '369b8c44a23e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fechamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_partida', sa.DateTime(), nullable=True),
    sa.Column('data_retorno', sa.DateTime(), nullable=True),
    sa.Column('User_id', sa.Integer(), nullable=True),
    sa.Column('Pacotes_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Pacotes_id'], ['pacotes.id'], ),
    sa.ForeignKeyConstraint(['User_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fechamento')
    # ### end Alembic commands ###
